title: 100DaysOfCode
author: author ahimsacode
# email: 100-days-of-code-github@ahimsa.33mail.com
# description:  # this means to ignore newlines until "baseurl:"

# social links
twitter_username: sacredtrouble # DO NOT include the @ character, or else the build will fail!
github_username:  ahimsacode # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
